
# SEO settings
title: "谢传发"
title2: "" # default: ""
description: "主要领域ios、android、ruby、java、react native."
keywords: "Jekyll, blog, web,ios android,ruby,java,react native"
url: https://akixie.github.io/ # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: https://github.com/akixie/akixie.github.com
disqus_shortname: "akixie"
twitter_username: "akixie1"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Aki"
  job      : "Software Engineer"
  bio      : "a balance between binary and reality."
  thumb    : /images/author.jpg
  email    : aki.c.xie@gmail.com
  url      : https://akixie.github.io/
  github   : https://github.com/akixie
  twitter  : https://twitter.com/akixie1
  # facebook : https://www.facebook.com/profile.php?id=1257583160
  # linkedin : http://linkedin.com/in/nrird

# social settings
# og_locale: "en_US"
# twitter_card: "summary_large_image"
# twitter_site: "@HeiswayiNrird"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: 关于我
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
